// This page was auto-generated by create-pages script
// Path: /imservice/invoices

export default function Page() {
  return (
    <div className="flex min-h-screen flex-col items-center justify-center p-4 text-center">
      <h1 className="text-3xl font-bold mb-4">Invoices</h1>
      <p className="text-gray-600">Path: /imservice/invoices</p>
    </div>
  )
}